# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FILE_NAME: reactjs-questions-answers
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create output directory
        run: |
          mkdir output  # create output dir          
      
      - name: Create PDF
        uses: docker://pandoc/latex:2.10
        with:
          args: --pdf-engine=xelatex --output=output/${{env.FILE_NAME}}.pdf README.md

      - name: Create epub
        uses: docker://pandoc/latex:2.10
        with:
          args: --output=output/${{env.FILE_NAME}}.epub README.md
      
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
